version: '3.8'

services:
  bot:
    build: .
    container_name: godje_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/app/data
      - ./prices.jpg:/app/prices.jpg
      - ./headset1.jpg:/app/headset1.jpg
      - ./headset2.jpg:/app/headset2.jpg
      - ./headset3.jpg:/app/headset3.jpg
      - ./headset4.jpg:/app/headset4.jpg
      - ./headset5.jpg:/app/headset5.jpg

volumes:
  db_data: